### ISSUE TITLE
About GPU settings

### ISSUE THREAD

**Issue by yarkable** [HikariTJU/LD#13]
Hi, in your paper, you use 2 GPUs in all your experiments except for SOTA experiments and 8 GPUs in SOTA experiments, is it? If it is, may I ask why?

**Comment by Zzh-tju** [comment]
8 GPU server are quite busy to get. We have several machines that only equip 2 GPUs. Thus we use 2 GPU settings in ablation for convenience. And we use 8 GPU settings in the SOTA experiment for fair comparison with other methods,  since it is common practice for that.

**Comment by yarkable** [comment]
Ok, I see. Thanks for your reply.
