### ISSUE TITLE
训练达不到论文的效果

### ISSUE THREAD

**Issue by kobesyy** [HikariTJU/LD#14]
安装您论文给的设置，在源码和mmdetection上都训练不到论文中的效果，甚至连原来gfl都没有，请问这是什么原因？是不是蒸馏后T的值要改变的问题？

**Comment by HikariTJU** [comment]
发下log

**Comment by kobesyy** [comment]
我可以加你个微信嘛，我的微信号 kobesyy1993



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: HikariTJU ***@***.***&gt;
发送时间: 2021年10月1日 10:07
收件人: HikariTJU/LD ***@***.***&gt;
抄送: kobesyy ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[HikariTJU/LD] 训练达不到论文的效果 (#14)





 
发下log
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HikariTJU** [comment]
加qq吧， 840918244

**Comment by Zzh-tju** [comment]
gpu数量和lr的设定要匹配，应该就没有别的特别需要注意的点了。温度T=10的性能是很稳定的，这也一直在我们其他实验中使用。你可以跑一下gfl的效果，看看它能达到的精度是否正常。
