### ISSUE TITLE
效果达不到论文以及config疑问

### ISSUE THREAD

**Issue by chenzyhust** [HikariTJU/LD#17]
1.使用teacher-r101-student-r18的config 1x训练结果：
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.323
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=1000 ] = 0.467
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=1000 ] = 0.350
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.179
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.345
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.415
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.538
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=300 ] = 0.538
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=1000 ] = 0.538
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=1000 ] = 0.317
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=1000 ] = 0.579
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=1000 ] = 0.707
结果差论文很多，这大概是什么原因？
2.config中只加载了teacher网络在coco上的训练好的模型，为啥student却是只加载了imagenet预训练的模型，不应该是基于训练好的coco模型蒸馏吗？感谢回答

**Comment by HikariTJU** [comment]
你是不是没改学习率

**Comment by chenzyhust** [comment]
> 

batch size 64设置的0.04，您这边16设置的0.01，有什么问题吗？

**Comment by HikariTJU** [comment]
要不你换成16， 0.01 跑试试？

**Comment by chenzyhust** [comment]
config的疑问方便解答一下吗？为啥是基于一个新的网络蒸馏。我再试试

**Comment by HikariTJU** [comment]
从coco接着训，相当于多训了几个epoch，从比较上了说不公平

**Comment by arifence** [comment]
> 从coco接着训，相当于多训了几个epoch，从比较上了说不公平

大家目标检测都从coco预训练模型开始训练啊，有没有coco预训练差好几个点呢，你这么比较是否有失公平

**Comment by HikariTJU** [comment]
> > 从coco接着训，相当于多训了几个epoch，从比较上了说不公平
> 
> 大家目标检测都从coco预训练模型开始训练啊，有没有coco预训练差好几个点呢，你这么比较是否有失公平

你说的是imagenet 吧
