### ISSUE TITLE
other models?

### ISSUE THREAD

**Issue by EdenBelouadah** [HikariTJU/LD#20]
Hello 
Firstly, thank you for this great work. 
Please, is it possible to use the code with whatever teacher/student model from mmdetection? 
I am interested to distill knowledge from a large model to  a very light student such as MobileNet, and use it for fast inference.

Thank you in advance

**Comment by HikariTJU** [comment]
If you mean backbone, then yes.
You can edit the backbone option in the config file to navigate different teacher/student.

**Comment by EdenBelouadah** [comment]
Thank you for your answer.
Yes, I would like to have a MobileNet as a student. Can you please tell me what to modify in this config file: 

https://github.com/HikariTJU/LD/blob/main/configs/ld/ld_r50_gflv1_r101_fpn_coco_1x.py

to have a resnet 50 as a teacher and a mobilenet as a student? 

I appreciate your help

**Comment by HikariTJU** [comment]
https://github.com/HikariTJU/LD/blob/34e3106e261d34cfd66d589d106225d18f3204a4/docs/tutorials/customize_models.md

**Comment by EdenBelouadah** [comment]
Thank you very much. This is so helpful.
