### ISSUE TITLE
On Self-LD

### ISSUE THREAD

**Issue by huangh12** [HikariTJU/LD#23]
@HikariTJU 你好， 在论文中有提到使用了Self KD可以涨点。 不过release的代码里，好像没有找到。
因为self KD的做法好像有好几种， 请问可以大概讲一下怎么做的吗？参考的哪篇论文呢？
谢谢！

**Comment by Zzh-tju** [comment]
文章这里说的不严谨，我们的self-LD指的是teacher与student是用相同的模型，而非在训练过程中自己教自己

**Comment by Zzh-tju** [comment]
比如你用训练1x的R50作为teacher，再去训一个新的R50 student

**Comment by huangh12** [comment]
那这个1x的R50 teacher是普通训练得到的，还是说用蒸馏训练得到的呢？

**Comment by HikariTJU** [comment]
普通

**Comment by huangh12** [comment]
明白了，谢谢！
