### ISSUE TITLE
retinagfl_r101_2x_coco.py训练问题

### ISSUE THREAD

**Issue by jczjcz** [HikariTJU/LD#24]
您好，我在最新版的mmdetection中增加了这个仓库中的`retinagfl_r101_2x_coco.py`文件和需要的一些head文件
代码的唯一改动是`retina_fl_head.py`中的Integral.forward()，因为直接跑会出现数字过大cuda报错，所以将
`x = F.linear(x, self.project.type_as(x)).reshape(-1, 4) `改成了
 `x = F.linear(x.reshape(4, -1, x.shape[-1]), self.project.type_as(x)).reshape(-1, 4)`
其他都是按照原配置运行实验，学习率设置为0.01，8卡，具体设置如下
[20220308_071908.log](https://github.com/HikariTJU/LD/files/8228421/20220308_071908.log)
但是实验结果非常糟糕，`2022-03-09 20:50:44,029 - mmdet - INFO - Epoch(val) [24][625]	bbox_mAP: 0.0010, bbox_mAP_50: 0.0020, bbox_mAP_75: 0.0000, bbox_mAP_s: 0.0000, bbox_mAP_m: 0.0000, bbox_mAP_l: 0.0020, bbox_mAP_copypaste: 0.001 0.002 0.000 0.000 0.000 0.002`
想问下是哪里出现了问题？

**Comment by HikariTJU** [comment]
我基于mmdetection 2.10改的, 现在出到2.20了可能有些地方不兼容吧。
一个简单的解决方案是直接用本仓库。
