### ISSUE TITLE
many gpus

### ISSUE THREAD

**Issue by eeric** [HikariTJU/LD#4]
how to set many gpus?

**Comment by HikariTJU** [comment]
./tools/dist_train.sh configs/ld/ld_gflv1_r101_r50_fpn_coco_1x.py 8

**Comment by eeric** [comment]
this script, it exist error: NCLL error

**Comment by HikariTJU** [comment]
`python3 -m torch.distributed.launch --nproc_per_node=2 --master_port 29501 tools/train.py configs/ld/ld_gflv1_r101_r50_fpn_coco_1x.py`

set nproc_per_node to how many gpus you want to use

**Comment by eeric** [comment]
I justly used this script, but only one gpu was occupied with two thread

**Comment by HikariTJU** [comment]
`python3 -m torch.distributed.launch --nproc_per_node=2 --master_port 29501 tools/train.py configs/ld/ld_gflv1_r101_r50_fpn_coco_1x.py --launcher pytorch`
Add --launcher option at the end works for me

**Comment by eeric** [comment]
add '--launcher pytorch', error,
add '--gpus 2', error below:
AssertionError: MMDataParallel only supports single GPU training, if you need to train with multiple GPUs, please use MMDistributedDataParallelinstead.

**Comment by HikariTJU** [comment]
What is the error when add '--launcher pytorch'

**Comment by eeric** [comment]
File "/home/user/work/LD/mmdet/models/dense_heads/ld_head.py", line 60, in reduce_mean
    dist.all_reduce(tensor.div_(dist.get_world_size()), op=dist.ReduceOp.SUM)
RuntimeError: result type Float can't be cast to the desired output type Long

**Comment by HikariTJU** [comment]
No idea.
The command works for me(python=3.7, pytorch=1.5.1, cuda=10.1) thought
Maybe you could try official mmdetection in which LD is included.

**Comment by eeric** [comment]
en

**Comment by eeric** [comment]
> ./tools/dist_train.sh configs/ld/ld_gflv1_r101_r50_fpn_coco_1x.py 8

here 8 was batch size, didn't it?

**Comment by HikariTJU** [comment]
GPU nums, batch size is set in the config file

**Comment by eeric** [comment]
ok, thanks.
