### ISSUE TITLE
请问Main 和 VLR 这两个区域是怎么确定的？

### ISSUE THREAD

**Issue by yangyangtiaoguo** [HikariTJU/LD#49]
作者你好，请问确定Main 和 VLR区域的原理是什么，看代码实在看懵了，不太了解检测

**Comment by HikariTJU** [comment]
可以看看论文，代码写得比较乱
Main: 正样本区域
VLR: 满足一定条件的负样本区域

**Comment by yangyangtiaoguo** [comment]
> 可以看看论文，代码写得比较乱 Main: 正样本区域 VLR: 满足一定条件的负样本区域

好的，我再看看论文。另外，我看到这两个区域的选择都来源于ATSS策略，但是VLR稍微有点不同（这个没太看懂），这两个区域有重叠嘛？

**Comment by HikariTJU** [comment]
这行是筛选VLR区域的代码
https://github.com/HikariTJU/LD/blob/2dda5c043e733c7cc40f6ce41fb37d0e76c44eeb/mmdet/core/bbox/assigners/atss_assigner.py#L272

简而言之就是 0.25threshold < diou < threshold 的点

**Comment by yangyangtiaoguo** [comment]
> 

明白啦！感谢回复~

**Comment by yangyangtiaoguo** [comment]
> 这行是筛选VLR区域的代码
> 
> https://github.com/HikariTJU/LD/blob/2dda5c043e733c7cc40f6ce41fb37d0e76c44eeb/mmdet/core/bbox/assigners/atss_assigner.py#L272
> 
> 简而言之就是 0.25threshold < diou < threshold 的点 并且同时要在GT区域内：
> 
> https://github.com/HikariTJU/LD/blob/2dda5c043e733c7cc40f6ce41fb37d0e76c44eeb/mmdet/core/bbox/assigners/atss_assigner.py#L154

明白啦！感谢回复~
