### ISSUE TITLE
setting parameter of LDLoss

### ISSUE THREAD

**Issue by eeric** [HikariTJU/LD#6]
at present, I modify and run through distillation code, using nanodet training framework.
setting parameter reduction='mean', loss_weight=1.0, T=2, alpha=1, beta=1 in LDLoss, did it?

[root][05-08 03:57:02]INFO:warmup|Iter(211/300)| lr:7.06e-02| loss_qfl:0.2829| loss_bbox:0.8766| loss_ld:0.0196| loss_dfl:0.3119| 
[root][05-08 03:57:10]INFO:warmup|Iter(221/300)| lr:7.39e-02| loss_qfl:0.2794| loss_bbox:0.8341| loss_ld:0.0250| loss_dfl:0.2975| 
[root][05-08 03:57:16]INFO:warmup|Iter(231/300)| lr:7.72e-02| loss_qfl:0.5848| loss_bbox:0.9857| loss_ld:0.0168| loss_dfl:0.3245|  
[root][05-08 03:57:23]INFO:warmup|Iter(241/300)| lr:8.05e-02| loss_qfl:0.2754| loss_bbox:0.9521| loss_ld:0.0166| loss_dfl:0.3287|
...
[root][05-08 04:00:07]INFO:train|Epoch1/300|Iter281(280/1543)| lr:1.00e-01| loss_qfl:0.2121| loss_bbox:0.6372| loss_ld:0.0287| loss_dfl:0.2452| 
[root][05-08 04:00:11]INFO:train|Epoch1/300|Iter291(290/1543)| lr:1.00e-01| loss_qfl:0.1914| loss_bbox:0.6420| loss_ld:0.0306| loss_dfl:0.2301|  
[root][05-08 04:00:15]INFO:train|Epoch1/300|Iter301(300/1543)| lr:1.00e-01| loss_qfl:0.2096| loss_bbox:0.6041| loss_ld:0.0293| loss_dfl:0.2287| 
[root][05-08 04:00:20]INFO:train|Epoch1/300|Iter311(310/1543)| lr:1.00e-01| loss_qfl:0.2008| loss_bbox:0.6006| loss_ld:0.0285| loss_dfl:0.2271| 
......

**Comment by HikariTJU** [comment]
Parameters are in config files, which is as follows:

loss_dfl=dict(type='LDLoss', loss_weight=0.25, T=10, alpha=1),

**Comment by eeric** [comment]
ok, thanks.
