### ISSUE TITLE
将DKD与LD结合的问题

### ISSUE THREAD

**Issue by 1014llj** [HikariTJU/LD#67]
您好，在阅读完LD后，我已成功复现[ld_r50_gflv1_r101_fpn_coco_1x.py](https://github.com/HikariTJU/LD/blob/bc60bbcd48e9305e61e32a0d2c981621e2ae0d05/configs/ld/ld_r50_gflv1_r101_fpn_coco_1x.py)，看到你们的知乎解析上有说LD + DKD的结合可能会有更好的效果，便尝试去将DKD结合到LD中，我在[kd_loss.py](https://github.com/HikariTJU/LD/blob/main/mmdet/models/losses/kd_loss.py)这个文件中模仿原有的kd_loss新加入了[dkd_loss](https://github.com/megvii-research/mdistiller/blob/master/mdistiller/distillers/DKD.py)，由于dkd需要labels去区分目标类和非目标类来计算损失，我在[ld_head.py](https://github.com/HikariTJU/LD/blob/main/mmdet/models/dense_heads/ld_head.py)文件的242行后和269行后分别加入了labels[pos_inds]和labels[remain_inds]，将labels的值传入kd_loss.py，并添加了一个新的[wrapper](https://github.com/HikariTJU/LD/blob/main/mmdet/models/losses/utils.py)与之适配，其他位置均未改动，之后我将[ld_r50_gflv1_r101_fpn_coco_1x.py ](https://github.com/HikariTJU/LD/blob/bc60bbcd48e9305e61e32a0d2c981621e2ae0d05/configs/ld/ld_r50_gflv1_r101_fpn_coco_1x.py)文件的第43行loss_kd的type改为新定义的dkd训练coco数据集，出现了以下错误
```
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block:[3,0,0], thread:[1,0,0] Assertion 'idx_dim >= 0 && idx_dim < index_size && "index out of bounds"' failed.
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block:[3,0,0], thread:[2,0,0] Assertion 'idx_dim >= 0 && idx_dim < index_size && "index out of bounds"' failed.
...
/opt/conda/conda-bld/pytorch_1659484810403/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:365: operator(): block:[3,0,0], thread:[31,0,0] Assertion 'idx_dim >= 0 && idx_dim < index_size && "index out of bounds"' failed.
terminate called after throwing an instance of 'c10::CUDAError'
CUDA error: device -side assert triggered
```
这个错误没有报出错的的位置，去查过可能是数组越界，但是无法定位到具体出错的位置，想请问下您有什么解决的建议吗？

**Comment by HikariTJU** [comment]
你能定位到是哪个数组越界了吗

**Comment by 1014llj** [comment]
您好，非常感谢您的回答，我不知道该如何定位数组越界问题，想请问您有什么好的方法，这是我的错误日志文件[20230515_203930.log](https://github.com/1014llj/log/blob/main/20230515_203930.log)，它没有报具体的错误位置，我不好定位，同时也想请问您觉得可能出错的位置有哪些？非常感谢

**Comment by HikariTJU** [comment]
你会用VS code的debug吗，它会在出错的地方停下来

**Comment by 1014llj** [comment]
好的，非常感谢，我去试一下VS code

**Comment by 1014llj** [comment]
你好，我自己试了下VS code，之前没有debug过这种模型训练的文件，不太清楚该如何debug，想请教您一下该如何使用VS code去debug，非常感谢。

**Comment by HikariTJU** [comment]
https://code.visualstudio.com/docs/python/debugging

**Comment by 1014llj** [comment]
好的，非常感谢您。

**Comment by yjq404** [comment]
@1014llj  同学你好，可以要一个你的联系方式吗？想交流一下蒸馏在检测中的应用

**Comment by 1014llj** [comment]
> @1014llj 同学你好，可以要一个你的联系方式吗？想交流一下蒸馏在检测中的应用
你好，WeChat：LLJ_234

**Comment by 1014llj** [comment]
> @1014llj 同学你好，可以要一个你的联系方式吗？想交流一下蒸馏在检测中的应用

你好，WeChat：LLJ_234 @yjq404
