### ISSUE TITLE
关于数据集minicoco

### ISSUE THREAD

**Issue by aowuaaa** [HikariTJU/LD#75]
您好，我看到您在别的issue提到过可以快速训练的minicoco，这个数据集是自己划分的还是已经做好的，如果是自己划分的如何能保证精度呢？谢谢

**Comment by HikariTJU** [comment]
minicoco只是一个用来调参的数据集，不能作为最终结果

**Comment by aowuaaa** [comment]
我的意思是coco太大了，我没有那么多卡跑，我也想弄一个minicoco调参使用

**Comment by HikariTJU** [comment]
我的意思是minicoco 不能保证精度

**Comment by aowuaaa** [comment]
好的好的，我明白了，谢谢谢谢
