### ISSUE TITLE
loadcheckpoint出现问题

### ISSUE THREAD

**Issue by 622tongtong** [HikariTJU/LD#79]
非常感谢您分享的代码！
当我下载教师网络的时候，出现问题：
missing keys in source state_dict:
missing keys是resnet101的layer 3的一些conv层，请问是什么原因呢？

**Comment by HikariTJU** [comment]
看下报错

**Comment by 622tongtong** [comment]
不好意思，我发现是自己把config写错了，没有问题了
&nbsp;


精彩人生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月18日(星期天) 上午9:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HikariTJU/LD] loadcheckpoint出现问题 (Issue #79)





 
看下报错
